name: StellarCrates
version: @version@
description: A crates to plugin to placate us.
authors: [viveleroi]
website:
api-version: @apiversion@
main: network.darkhelmet.stellarcrates.StellarCrates
depend: [DecentHolograms,PlaceholderAPI]
softdepend: [SpecializedCrates]

